---
title: "Resume"
---

####Education:

Bachelor of Science, Psychology (Natural Science Concentration)

Appalachian State University, Boone NC

Minor: Military Science, Chemistry, and Statistics

GPA: 3.77

####Honors:

* Invited to Dean’s and Chancellor’s list throughout college

* Nominated multiple times for the Plemmons Student Leadership Award'

####Extracurriculars:

* Participation in a nationally recognized community service group, Scabbard and Blade, with a leadership
position of treasurer

* Participation in running club with a leadership position of secretary

* Participation in Archery club

* Participation in Communications club, Appspeaks, and helped organize student-led conferences

* ROTC involvement: help leadership positions during training and used them to educate underclassmen

* TEDxAppalachianStateUniversity curator

####Work Experience:
######University Tutor
* Appalachian State, Boone

* August 2016 to current, tutored in statistics, biology, chemistry, and neuroscience.

######Data Analyst and Program Learner

* Appalachian State, Boone

* Fall Semester 2017, worked with other students to develop videos used in a religion class to teach

* students statistical programs.

######Clinical Psychology Internship

* San Antonio, Brooke Army Medical Center

* Summer 2018, practiced clinical psychology through neuroscience, pharmacology, and psychotherapy.

####Volunteer Experience:

######National Honor Society
* August 2013 to June 2015, volunteered 20 hours per semester in various organizations including Habitat
for Humanity, academic tutoring, and school-sponsored organizations.

######Scabbard and Blade
* Cooperated with peers to coordinate events to better of the community. As treasurer I budgeted and
allocated the club’s finances.

######TEDxAppalachianStateUniversity Curator and Manager
* Pioneered the first and second TEDx conferences at Appalachian State in Spring 2017 and 2018 by finding
speakers, organizing the event, and working with the Scabbard and Blade club to promote the event.

####Research Experience:
* Research assistant in Appalachian State’s Behavioral Neuroscience Lab.

* Presented research at the National Conference of Undergraduate Research (NCUR) in spring of 2018

* Publishing in NCUR proceedings in November 2018

* Presenting a poster at the Society for Neuroscience in November 2018